# Generated by Django 4.1.1 on 2022-09-19 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_books', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=256)),
                ('release_year', models.IntegerField()),
                ('state', models.CharField(max_length=56)),
                ('pages', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=256)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
